### ISSUE TITLE
Allow JSON export on iOS

### ISSUE THREAD

**Issue by zeeMonkeez** [design-first/system-designer#103]
For issues give the following informations related to your problem: 

- System Designer version number: *v2.8.3*
- System Designer platform: *iOS*
- Your OS version: *iOS 11.4*
- If use on a phone, please give the model: *iPhone 6s, iPad mini 4*

I would love to be able to export my systems as JSON on the iPad or iPhone. While GitHub integration is great, we use BitBucket and some other data sharing solutions. Supporting generic ‘copy as JSON’ would go a long way.

**Comment by ecarriou** [comment]
In order to simplify the UI on mobile, I have deactivated this feature on mobile. So I will enable it.

To do so I will enable the *Advanced mode* checkbox on the Configuration panel. 
This checkbox will show a *Bundle* menu on top when you edit a system. 
When you click on it, you will see the JSON generated for the system and you will be able to select/copy/paste it with native iOS menu.

**Comment by ecarriou** [comment]
Fixed with commit https://github.com/design-first/system-designer-cordova/commit/b27d096cf2cd5abf37f09b3eb57e1beb02844ca4

**Comment by ecarriou** [comment]
Version will be available on App Store next week (for System Designer v2.8.4).
